### PR TITLE
fix: trigger media type validation only when defined in the response

### LINKED ISSUE #774: Do not validate the output media type if the document does not specify any content
@StefanDywersant ahh well this just shows that my next job of "play with proxy server and contract testing to make sure it works as expected" should have been done sooner. My bad. 

If the API does not specify content, then anything which comes in is a bonus, maybe a warning or an info, but certainly not an error. It's the sort of thing we'd report to folks via Studio somehow (long way off) saying "Hey we found some content, looks like this is JSON, here is the schema. Wanna save that to your description?" etc.

How do I make a callback which says "I dont care what they respond with im just looking for a 200? A lot of callbacks work this way, they just want a "Yep!" and nothing more.

_Originally posted by @philsturgeon in https://github.com/stoplightio/prism/pull/716#issuecomment-550370944_

### PR DESCRIPTION
**Pull request by XVincentX**
Closes #774

* Calls the media type return validator only if the selected response has contents with a media type
* Uses now `typeIs.is` function library so that we can match stuff with charset headers as well instead of a simple equality check

### CODE REVIEW

File: packages/http/src/validator/index.ts [hunk 1]
```diff
@@ -84,14 +91,13 @@ const findResponseByStatus = (responses: NonEmptyArray<IHttpOperationResponse>,
...
-    Option.fromNullable(response.contents),
-    Option.chain(findFirst(c => c.mediaType === mediaType)),
+    contents,
+    findFirst(c => !!typeIs.is(mediaType, [c.mediaType])),
     Either.fromOption<IPrismDiagnostic>(() => ({
-      message: `The received media type "${
-        mediaType ? mediaType : ''
-      }" does not match the one specified in the document`,
+      message: `The received media type "${mediaType ||
+        ''}" does not match the one specified in the current response: ${contents.map(c => c.mediaType).join(',')}`,
```
Comment (StefanDywersant) [inline packages/http/src/validator/index.ts]:
```suggestion
        ''}" does not match the one${contents.length ? 's' : ''} specified in the current response: ${contents.map(c => c.mediaType).join(', ')}`,
```
