### PR TITLE
fix: return correct error code based on the validation type

### LINKED ISSUE #591: When request doesn't contain proper security scheme, return the user-defined 401 first
When a request to an endpoint does not meet the security scheme (i.e, lacking bearer token), Prism currently looks for a 422 definition, followed by a 400 definition, followed by 401.  This seems odd, if we have our own 401 defined, it should be the first one tried by Prism.

**To Reproduce**

1. Given an endpoint defined like so:

```
/users:
    get:
      summary: "Retrieves the authenticated user"
      description: "Returns the `user` object associated with the bearer token in the Authorization header."
      responses:
        200:
          $ref: '#/components/responses/SuccessfulUserResponse'
        400:
          description: "The provided user data was malformed, or attempted to modify a read-only field (such as `balance`)."
        401:
          $ref: '#/components/responses/InvalidAuthorizationTokenResponse'
```

2. Curl the endpoint without an "Authorization: Bearer" token
3. Prism log:

```
    [VALIDATOR] ⚠  warning   Request did not pass the validation rules
    [NEGOTIATOR] ●  note      Unable to find a 422 response definition
    [NEGOTIATOR] ✔  success   Found response 400. I'll try with it.
    [NEGOTIATOR] ●  note      Unable to find a content with an example defined for the response 400
    [NEGOTIATOR] ✔  success   The response 400 has a schema. I'll keep going with this one
    [NEGOTIATOR] ✔  success   Responding with the requested status code 400
```

**Expected behavior**
That the 401 we defined would be used first, before trying 422/400 since this is explicitly an authorization failure.

### PR DESCRIPTION
**Pull request by XVincentX**
1. Remove 403 leftovers
2. Generalize the `findResponse` so that somebody can provide an array of what we're looking for
3. Look fo the right response according to the validation type (security comes first, validation comes later)

Closes #591

### CODE REVIEW

File: packages/http/src/mocker/negotiator/NegotiatorHelpers.ts [hunk 1]
```diff
@@ -248,22 +249,28 @@ const helpers = {
...
-          logger.trace('Unable to find a 400 response definition.');
-          return findResponseByStatusCode(httpResponses, '401');
-        }),
-        Option.alt(() => findResponseByStatusCode(httpResponses, '403')),
+        others.reduce(
+          (previous, current, index) =>
+            pipe(
+              previous,
+              Option.alt(() => {
+                logger.trace(`Unable to find a ${statusCodes[index === 0 ? first : 1 + index]} response definition`);
```
Comment (lag-of-death) [inline packages/http/src/mocker/negotiator/NegotiatorHelpers.ts]: @XVincentX,
if `statusCodes` equals ['400', '422', '404'], then
for `index === 0`: statusCodes['400'],
for `index === 1`: statusCodes['2']
for `index === 2`: statusCodes['3']

or am I reading this wrong?

Comment (XVincentX) [reply packages/http/src/mocker/negotiator/NegotiatorHelpers.ts]: That's effectively wrong, I've fixed it.

File: CHANGELOG.md [hunk 2]
```diff
@@ -13,6 +13,7 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 - Prism is now giving precedence to `application/json` instead of using it as a "fallback" serializer, fixing some conditions where it wouldn't get triggered correctly. [#604](https://github.com/stoplightio/prism/pulls/604)
 - Prism is now taking in consideration the `required` properties for combined schemas (`oneOf, allOf`). This is coming through an update to the Json Schema Faker Library [#623](https://github.com/stoplightio/prism/pulls/623)
 - Prism will never have enough information to return a `403` status code; all these occurences have been now replaced with a `401` status code which is more appropriate [#625](https://github.com/stoplightio/prism/pulls/625)
+- Prism is now negotiating the error response dinamically based on the validation result (security or schema validation) instead of always returning a static order of responses [#628](https://github.com/stoplightio/prism/pulls/628)
```
Comment (lag-of-death) [inline CHANGELOG.md]:
```suggestion
- Prism is now negotiating the error response dynamically based on the validation result (security or schema validation) instead of always returning a static order of responses [#628](https://github.com/stoplightio/prism/pulls/628)
```

File: test-harness/specs/security-scheme-validation-AC-27.oas2.txt [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+    schema:
+      type: string
+      example:
+        abc
+  InvalidPayload:
+    description: InvalidPayload
+    schema:
+      type: string
+      example:
+        abc
```
Comment (philsturgeon) [inline test-harness/specs/security-scheme-validation-AC-27.oas2.txt]: might be worth having different example values for things like this just to make sure the body isnt mismatching somehow.

Comment (XVincentX) [reply test-harness/specs/security-scheme-validation-AC-27.oas2.txt]: I did it for oas3, didn't do it for oas2. Fixed.
